export const DummyData = [
  {
    title: "Macbook",
    owner: "Superman",
    description: "Condition is excellent",
    price: "$100",
    category: "Computer",
    user_id: 1,
  },
  {
    title: "Camera 3000",
    owner: "Batman",
    description: "This amazing camera will be perfect for any of your needs.",
    price: "$10",
    category: "Camera",
    user_id: 1,
  },
  {
    title: "PC",
    owner: "Bobby",
    description: "Its here if u want, I will also consider selling",
    price: "$50",
    category: "PC",
    user_id: 1,
  },
  {
    title: "Camera spec6X",
    owner: "Iron Man",
    description: "This amazing camera will be perfect for any of your needs.",
    price: "$50",
    category: "Camera",
    user_id: 1,
  },
  {
    title: "iPad 5 X pro",
    owner: "Iron Man",
    description: "This amazing camera will be perfect for any of your needs.",
    price: "$50",
    category: "Tablet",
    user_id: 1,
  },
  {
    title: "Camera X",
    owner: "Iron Man",
    description: "This amazing camera will be perfect for any of your needs.",
    price: "$50",
    category: "Camera",
    user_id: 1,
  },
];
